[package]
name = "tezos_interop"
version = "0.0.3"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
futures = { version = "0.3", features = ["thread-pool"] }
hex = "0.4"
lazy_static = "1.4"
ocaml = "0.9.3"
serde_json = "1.0"
# local dependencies
tezos_api = { path = "../api" }
tezos_encoding = { path = "../encoding" }
tezos_interop_callback = { path = "../interop_callback" }

[build-dependencies]
colored = "1.8.0"
fs_extra = "1.1.0"
hex = "0.4"
os_type = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.8.0"

[dev-dependencies]
crypto = { path = "../../crypto" }
tezos_context = { path = "../context" }
tezos_messages = { path = "../messages" }
serial_test = "0.4"
