[package]
name = "tezos_interop"
version = "0.0.1-pre18-context"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
futures-preview = "0.3.0-alpha.19"
hex = "0.4"
lazy_static = "1.4"
# TODO: change when ocaml = "0.9.0" because of Array1::from
ocaml = { git = "https://github.com/simplestaking/ocaml-rs.git", branch = "master" }
serde_json = "1.0"
# local dependencies
tezos_api = { path = "../api" }
tezos_interop_callback = { path = "../interop_callback" }

[build-dependencies]
colored = "1.8.0"
fs_extra = "1.1.0"
hex = "0.4"
os_type = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.8.0"