http_v2 = 17732

[[nodes]]
name = "9732"
db = "/tmp/debugger_database/tezedge"
p2p = { identity = "/tmp/volume/tezedge/identity.json", port = 9732 }
log = { port = 10001 }

[[nodes]]
name = "9733"
db = "/tmp/debugger_database/tezos"
p2p = { identity = "/tmp/volume/tezos/data/identity.json", port = 9733 }
log = { port = 11001 }
