---
##############################################################################################################
# This pipeline runs tezedge node with florencenet configuration againts ocaml node with florencenet snapshot
##############################################################################################################
kind: pipeline
name: florencenet-performance-tests

clone:
  disable: true

node:
  tag: real-time-linux-runner

environment:
  NETWORK: florencenet
  FROM_BLOCK_HEADER: 0
  TO_BLOCK_HEADER: 600 # also check parameter --stop=
  TOP_BLOCK_HEADER: 20000 # also check parameter --stop=
  WRK_TEST_BLOCK_HEADER: 100
  WRK_TEST_BLOCK_HASH: BMVqWVfTkwDCuBJNvV3scVVXd9X2HMq3qcxo4jkAyJ7NvfHnwdG
  SODIUM_USE_PKG_CONFIG: 1
  OCAML_NODE_RPC_CONTEXT_ROOT_1: http://ocaml-node-florencenet-run-1:8732
  OCAML_NODE_RPC_CONTEXT_ROOT_2: http://ocaml-node-florencenet-run-2:8732
  OCAML_NODE_RPC_CONTEXT_ROOT_3: http://ocaml-node-florencenet-run-3:8732
  OCAML_NODE_P2P_PEERS: ocaml-node-florencenet-run-1:9734,ocaml-node-florencenet-run-2:9734,ocaml-node-florencenet-run-3:9734
  TEZEDGE_NODE_RPC_CONTEXT_ROOT: http://tezedge-updated-node-florencenet-run:18732
  TEZEDGE_NODE_TARGET_BRANCH_RPC_CONTEXT_ROOT: http://tezedge-old-node-florencenet-run:18732
  OCAML_NODE_INDEXER_ROOT: http://tz-indexer-florencenet-ocaml:8002
  TEZEDGE_NODE_INDEXER_ROOT: http://tz-indexer-florencenet-tezedge:8002
  BUILD_ARTIFACTS_PATH: /artifacts/build_${DRONE_BUILD_NUMBER}
  TEST_ARTIFACTS_PATH: /tests/build_${DRONE_BUILD_NUMBER}
  CACHE_DATA_PATH: /data/cache/build_${DRONE_BUILD_NUMBER}/florencenet-offline-tests
  WRK_TEST_DURATION: 10  # in seconds
  WRK2_TEST_DURATION: 30  # in seconds
  WRK2_REQ_RATE: 100 # per second

steps:
  - name: prepare-data
    image: alpine/git
    user: root
    volumes:
      - name: cache
        path: /data/cache
    commands:
      - rm -rf $${CACHE_DATA_PATH}
      - mkdir -p $${CACHE_DATA_PATH}

  # just run ocaml 3 florencenet snapshoted nodes
  - name: ocaml-node-florencenet-run-1
    user: root
    image: tezos/tezos:v9-release
    detach: true
    volumes:
      - name: build
        path: /artifacts
      - name: ocaml-node-florencenet-snapshot-data-1
        path: /home/tezos/data
      - name: cache
        path: /data/cache
    commands:
      - ip -o -4 addr show | awk -F '[ /]+' '/global/ {print $4 ":9734"}' > $${CACHE_DATA_PATH}/ocaml_ip1.txt
#      - rm -f /home/tezos/data/lock
#      - cp $${BUILD_ARTIFACTS_PATH}/build_files/identities/identity_1.json /home/tezos/data/identity.json
#      - tezos-node config reset --data-dir /home/tezos/data --network $${NETWORK} --no-bootstrap-peers
      - tezos-node run --data-dir /home/tezos/data --history-mode archive --rpc-addr 0.0.0.0:8732 --net-addr 0.0.0.0:9734 --network $${NETWORK} --no-bootstrap-peers


  - name: wait-for-ocaml-snapshoted-nodes
    image: simplestakingcom/tezos-node-bootstrap:latest
    commands:
      - tezos-node-bootstrap bootstrap --level=$${TOP_BLOCK_HEADER} --nodes $${OCAML_NODE_RPC_CONTEXT_ROOT_1}


  # now we have prepared ocaml and tezedge node, that can run tests - rpc, wrk, indexer-test

  - name: conseil-indexing-rpc-sequence
    image: busybox
    volumes:
      - name: perf
        path: /perf
    commands:
      - time -f "%E" -o tezos.time xargs -a /perf/conseil-rpc-list.txt -n 1 -i wget -O /dev/null -q $${OCAML_NODE_RPC_CONTEXT_ROOT_1}{}
      - 'echo "Ocaml node time:       $(tezos.time)"'

image_pull_secrets:
  - docker_pull_secret

volumes:
  - name: perf
    host:
      path: /usr/local/etc/tezedge-ci/perf
  - name: build
    host:
      path: /usr/local/etc/tezedge-ci/build
  - name: tests
    host:
      path: /usr/local/etc/tezedge-ci/tests/
  - name: ocaml-node-florencenet-snapshot-data-1
    host:
      path: /usr/local/etc/tezedge-ci/data/ocaml-node-florencenet-snapshot-data-with-identity-1
#      path: /usr/local/etc/tezedge-ci/data/ocaml-node-florencenet-snapshot-data-1
  - name: ocaml-node-florencenet-snapshot-data-2
    host:
      path: /usr/local/etc/tezedge-ci/data/ocaml-node-florencenet-snapshot-data-2
  - name: ocaml-node-florencenet-snapshot-data-3
    host:
      path: /usr/local/etc/tezedge-ci/data/ocaml-node-florencenet-snapshot-data-3
  - name: cache
    host:
      path: /usr/local/etc/tezedge-ci/data/cache
  - name: indexer-tezedge-data
    temp: {}
  - name: indexer-ocaml-data
    temp: {}

trigger:
  branch:
    - master
    - develop

#depends_on:
#  - build
