---
kind: pipeline
name: florencenet-tzkt-tezos-indexer-test

clone:
  disable: true

environment:
  NETWORK: florencenet

volumes:
  - name: cache
    host:
      path: /usr/local/etc/tezedge-ci/data/cache/build_${DRONE_BUILD_NUMBER}/${DRONE_STAGE_NAME}
  - name: tezos-data
    host:
      path: /usr/local/etc/tezedge-ci/data/ocaml-node-florencenet-snapshot-data-with-identity-small
  - name: conseil-sql
    temp: {}

trigger:
  branch:
    - develop

depends_on:
  - build

steps:

  - name: tezos-node
    user: root
    image: tezos/tezos:v9-release
    detach: true
    volumes:
      - name: tezos-data
        path: /home/tezos/data
      - name: cache
        path: /cache
    commands:
      - tezos-node run --data-dir /home/tezos/data --history-mode archive --network $${NETWORK} --no-bootstrap-peers --rpc-addr 0.0.0.0:8732

  - name: tzkt-postgres
    image: postgres:13
    detach: true
    environment:
      POSTGRES_USER: tzkt
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: tzkt_db
    volumes:
      - name: postgres
        path: /var/lib/postgresql/data

  - name: tzkt-sync
    image: bakingbad/tzkt-sync:latest
    volumes:
      - name: cache
        path: /cache
    environment:
      TZKT_ConnectionStrings__DefaultConnection: "server=tzkt-postgres;port=5432;database=tzkt_db;username=tzkt;password=qwerty;"
      TZKT_TezosNode__ChainId: NetXxkAx4woPLyu
      TZKT_TezosNode__Endpoint: http://tezos-node:8732/
      TZKT_TezosNode_Timeout: 60
    commands:
      - apt-get update && apt-get install time
      - sleep 5
      - cd /app
      - time -f "%E" -o /cache/time sh -c 'dotnet Tzkt.Sync.dll > /tmp/tzkt.log & sleep 1; tail -f /tmp/tzkt.log | awk "/Applied .*0 of/ { print } /Applied 100 of/ { exit }"; kill $$!'

  - name: report-time
    image: busybox
    volumes:
      - name: cache
        path: /cache
    commands:
      - echo "============== indexing time ============="
      - cat /cache/time

