language: rust
rust:
  - nightly-2019-12-05

os:
  - linux

dist: xenial

sudo: false

env:
  global:
    - RUST_BACKTRACE=1
    - SODIUM_USE_PKG_CONFIG=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - g++
      - llvm-dev
      - libclang-dev
      - clang
      - libsodium-dev
      - libev4
      - libssl-dev

branches:
  only:
    - master

services:
  - docker

before_install:
  - export CURRENT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - bash run.sh travis

install:
  - travis_wait 60 cargo build --verbose

script:
  - cargo test --verbose
  - cargo test --verbose -- --nocapture --test-threads=1 --ignored integ_test