language: rust
rust:
  - nightly-2020-05-15

os:
#  - linux
  - osx

dist: focal

sudo: false

env:
  global:
    - RUST_BACKTRACE=1
    - SODIUM_USE_PKG_CONFIG=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - g++
      - llvm-dev
      - libclang-dev
      - clang
      - libsodium-dev
      - libev4
  homebrew:
    update: true
    packages:
      - pkg-config
      - gmp
      - libev
      - libsodium

before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew cleanup
      find /usr/local/Homebrew \! -regex ".+\.git.+" -delete
    fi

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

branches:
  only:
    - master
    - develop