language: rust
rust:
  - nightly-2020-05-15

os:
#  - linux
  - osx

dist: focal

sudo: false

env:
  global:
    - RUST_BACKTRACE=1
    - SODIUM_USE_PKG_CONFIG=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - g++
      - llvm-dev
      - libclang-dev
      - clang
      - libsodium-dev
      - libev4
  homebrew:
    update: true
    packages:
      - pkg-config
      - libev
      - libsodium

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      mkdir ~/.cargo;
      echo -e "[build]\nrustflags = [\"-C\", \"link-args=-Wl,-undefined,dynamic_lookup\"]" > ~/.cargo/config;
    fi;

branches:
  only:
    - master
    - develop