language: rust
rust:
  - nightly-2019-12-05

os:
  - linux

dist: xenial

sudo: false

env:
  global:
    - RUST_BACKTRACE=1
    - SODIUM_USE_PKG_CONFIG=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - g++
      - llvm-dev
      - libclang-dev
      - clang
      - libsodium-dev
      - libev4
      - libssl-dev

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker pull tezos/tezos:babylonnet
  - docker run --rm -d -p 8732:8732 --name ocaml-node tezos/tezos:babylonnet tezos-node

install:
  - travis_wait 40 cargo build --verbose