language: rust
rust:
  - nightly-2019-12-05

os:
  - linux

dist: xenial

sudo: false

env:
  global:
    - RUST_BACKTRACE=1
    - SODIUM_USE_PKG_CONFIG=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - g++
      - llvm-dev
      - libclang-dev
      - clang
      - libsodium-dev
      - libev4
      - libssl-dev

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker pull otisak/travis-tezedge:latest
  - export CURRENT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export GIT_CMD=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "git checkout $CURRENT_BRANCH"; else echo "git fetch origin pull/$TRAVIS_PULL_REQUEST/head:$CURRENT_BRANCH && git checkout $CURRENT_BRANCH"; fi)
  - docker run -d --net host -m 4g --name tezedge-node --entrypoint /bin/bash otisak/travis-tezedge:latest -c "$GIT_CMD && ./run.sh release"
  - docker ps -a

install:
  - cargo build --verbose

script:
  - cargo test --verbose
  - cargo test --verbose -- --nocapture --test-threads=1 --ignored integ_test