version: "3"

services:

  tezedge-debugger:
    image: simplestakingcom/tezedge-debugger:latest-release
    privileged: true
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - "tezedge-shared-data:/tmp/volume/tezedge:ro"
      - "./docker-compose.debug.debugger-config.toml:/home/appuser/config.toml:ro"
      - "/sys/kernel/debug:/sys/kernel/debug:rw"
      - "/tmp/report:/tmp/report:rw"
      - "debugger-data:/tmp/debugger_database"
    ports:
      - "17732:17732"      # debugger RPC port
      - "10001:10001/udp"  # debugger syslog port for tezedge node

  tezedge-node:
    image: simplestakingcom/tezedge:latest-release
    command: ["--network", "${TEZOS_NETWORK-mainnet}", "--p2p-port=9732", "--rpc-port=18732", "--websocket-address=0.0.0.0:4927", "--log", "terminal", "file", "--log-file", "/tmp/tezedge/tezedge.log", "--peer-thresh-low", "30", "--peer-thresh-high", "45", "--tezos-context-storage=${TEZOS_CONTEXT_STORAGE:-irmin}"]
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:10001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "tezedge-shared-data:/tmp/tezedge"
    ports:
      - "4927:4927"       # node WS port (required only for tezedge)
      - "9732:9732"       # node P2P port
      - "18732:18732"     # node RPC port

  explorer:
    image: simplestakingcom/tezedge-explorer:latest-release
    environment:
      - DEBUGGER=http://localhost:17732
      # need a better way to provide such information
      - API=[{"id":"tezedge","name":"tezedge","http":"http://localhost:18732","debugger":"http://localhost:17732","ws":"ws://localhost:4927","monitoring":"","p2p_port":9732,"features":["MONITORING","STORAGE_BLOCK", "MEMPOOL_ACTION","NETWORK_ACTION","LOGS_ACTION"]}]
    ports:
      - "80:80"
      - "8080:80"

volumes:
  tezedge-shared-data:
    external: false
  debugger-data:
    external: false