[package]
name = "tezos_interop"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.18"
lazy_static = "1.3.0"
log = "0.4.8"
ocaml = "0.7.0"

[build-dependencies]
fs_extra = "1.1.0"