[package]
name = "rpc"
version = "0.9.0"
authors = ["Martin Lacko <martin.lacko@simplestaking.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
getset = "0.1"
failure = "0.1"
futures = "0.3"
hex = "0.4"
hyper = "0.13"
itertools = "0.9"
path-tree = "0.1.9"
riker = "0.4"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
slog = { version = "2.5", features = ["nested-values"] }
tokio = { version = "0.2", features = ["macros", "time"] }
rayon = "1.3"
bytes = "0.5"
# local dependencies
crypto = { path = "../crypto" }
shell = { path = "../shell" }
storage = { path = "../storage" }
tezos_api = { path = "../tezos/api" }
tezos_context = { path = "../tezos/context" }
tezos_messages = { path = "../tezos/messages" }
tezos_wrapper = { path = "../tezos/wrapper" }

[dev-dependencies]
assert-json-diff = "1.0.0"
enum-iterator = "0.6"
rand = "0.7.3"