[package]
name = "logging"
version = "1.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"


[dependencies]
chrono = "0.4"
libflate = "1"
nix = "0.19"
serde = { version = "1.0", features = ["derive"] }
slog = "2.7"
slog-json = "2.3"

[dev-dependencies]
tempfile = "3"