[package]
name = "networking"
version = "1.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bytes = "1"
failure = "0.1"
futures = "0.3"
hex = "0.4"
riker = "0.4"
slog = "2.7"
tokio = { version = "1.2", features = ["time", "net"] }
# local dependencies
crypto = { path = "../crypto" }
tezos_encoding = { path = "../tezos/encoding" }
tezos_identity = { path = "../tezos/identity" }
tezos_messages = { path = "../tezos/messages" }
