[package]
name = "tezos_encoding"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bit-vec = "0.6.2"
byteorder = "1.3.2"
bytes = "0.5"
chrono = "0.4.9"
failure = "0.1"
hex = "0.4"
num-bigint = "0.2.2"
num-traits = "0.2.8"
serde = { version = "1.0", features = ["derive"] }
# local dependencies
crypto = { path = "../../crypto" }