[package]
name = "tezos_encoding"
version = "1.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bit-vec = "0.6.2"
byteorder = "1.4"
bytes = "1"
chrono = "0.4"
failure = "0.1"
hex = "0.4"
num-bigint = "0.3"
num-traits = "0.2.8"
serde = { version = "1.0", features = ["derive"] }
# local dependencies
crypto = { path = "../../crypto" }