[package]
name = "storage"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
failure = "0.1.5"
rocksdb = "0.12.3"
slog = "2.5"
networking = { path = "../networking" }
tezos_encoding = { path = "../tezos/encoding" }
