[package]
name = "storage"
version = "0.9.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bincode = "1.3"
blake2 = "0.9"
bytes = "0.5"
commitlog = "0.1"
derive_builder = "0.9"
failure = "0.1"
getset = "0.1"
hex = "0.4"
im = { version = "15.0.0", features = ["serde"] }
itertools = "0.9"
num_cpus = "1.13"
rocksdb = "0.15"
serde = { version = "1.0", features = ["derive", "rc"] }
slog = "2.5"
# local dependencies
crypto = { path = "../crypto" }
tezos_api = { path = "../tezos/api" }
tezos_context = { path = "../tezos/context" }
tezos_messages = { path = "../tezos/messages" }

[dev-dependencies]
assert-json-diff = "1.0.0"
hex = "0.4"
maplit = "1.0"
rand = "0.7.3"
serde_json = "1.0"
slog-async = "2.5"
slog-term = "2.6"
