[package]
name = "storage"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
networking = { path = "../networking" }
tezos_encoding = { path = "../tezos_encoding" }