[package]
name = "storage"
version = "0.0.3"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bincode = "1.2"
bytes = "0.5"
commitlog = "0.1"
derive_builder = "0.9"
failure = "0.1"
getset = "0.0.9"
hex = "0.4"
rocksdb = "0.13"
serde = { version = "1.0", features = ["derive", "rc"] }
slog = "2.5"
lazy_static = "1.4"
itertools = "0.9"
# local dependencies
crypto = { path = "../crypto" }
tezos_api = { path = "../tezos/api" }
tezos_context = { path = "../tezos/context" }
tezos_encoding = { path = "../tezos/encoding" }
tezos_messages = { path = "../tezos/messages" }

[dev-dependencies]
hex = "0.4"
rand = "0.7.3"
maplit = "1.0"
slog-async = "2.3"
slog-term = "2.4"