[package]
name = "storage"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bincode = "1.2"
bytes = "0.4"
commitlog = "0.1"
failure = "0.1"
rocksdb = "0.12"
serde = { version = "1.0", features = ["derive"] }
slog = "2.5"
# local dependencies
crypto = { path = "../crypto" }
networking = { path = "../networking" }
tezos_context = { path = "../tezos/context" }
tezos_encoding = { path = "../tezos/encoding" }
tezos_messages = { path = "../tezos/messages" }

[dev-dependencies]
hex = "0.4"