[package]
name = "storage"
version = "1.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bincode = "1.3"
blake2 = "0.9"
commitlog = "0.1"
derive_builder = "0.9"
failure = "0.1"
getset = "0.1"
hex = "0.4"
itertools = "0.10"
num_cpus = "1.13"
rocksdb = {version = "0.15", features = ["snappy", "lz4", "zstd", "zlib"], default-features = false }
serde = { version = "1.0", features = ["derive", "rc"] }
slog = "2.7"
# local dependencies
crypto = { path = "../crypto" }
snap = "1.0.4"
tezos_api = { path = "../tezos/api" }
tezos_context = { path = "../tezos/context" }
tezos_messages = { path = "../tezos/messages" }
sled = "0.34.6"
bytes = "1.0.1"

[[bench]]
name = "predecessor_benchmarks"
harness = false

[dev-dependencies]
assert-json-diff = "1.1"
hex = "0.4"
maplit = "1.0"
rand = "0.7.3"
serde_json = "1.0"
slog-async = "2.6"
slog-term = "2.6"
criterion = "0.3"
