[package]
name = "test_tezos_interop"
version = "0.0.1"
edition = "2018"
publish = false

[dev-dependencies]
futures-preview = "0.3.0-alpha.17"
ocaml = "0.7.0"
tezos_interop = { path = "../../tezos_interop" }
