[package]
name = "light-node"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
dirs = "1.0.4"
failure = "0.1.5"
hex = "0.3.2"
lazy_static = "1.3.0"
log = "0.4.8"
log4rs = { version = "0.8.3", features = ["rolling_file_appender", "compound_policy", "size_trigger", "fixed_window_roller"] }
riker = { git = "https://github.com/riker-rs/riker" }
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
tokio = "0.2.0-alpha.2"
# Local dependencies
tezos_encoding = { path = "../tezos_encoding" }
crypto = { path = "../crypto" }
networking = { path = "../networking" }
storage = { path = "../storage" }