[package]
name = "tezos_client"
version = "1.1.0"
authors = ["Branislav Kontur <branislav.kontur@simplestaking.com>"]
edition = "2018"

[dependencies]
crypto = { path = "../../crypto" }
tezos_api = { path = "../api" }
tezos_interop = { path = "../interop" }
tezos_messages = { path = "../messages" }

[dev-dependencies]
assert-json-diff = "1.1"
enum-iterator = "0.6"
failure = "0.1"
hex = "0.4"
serde_json = "1.0"
serial_test = "0.5"
