[package]
name = "tezos_interop_callback"
version = "1.4.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
ocaml-interop = { version = "0.8.3", features = ["without-ocamlopt", "caml-state"] }
# local dependencies
tezos-sys = { path = "../sys" }
tezos_context = { path = "../context" }
