[package]
name = "tezos_interop_callback"
version = "1.5.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
ocaml-interop = { version = "0.8.1" }
# local dependencies
tezos-sys = { path = "../sys" }
tezos_context = { path = "../context" }
