[package]
name = "tezos_interop_callback"
version = "0.7.2"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
ocaml-interop = "0.2.2"
# local dependencies
tezos_context = { path = "../context" }
