[package]
name = "tezos_wrapper"
version = "1.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
getset = "0.1"
failure = "0.1"
failure_derive = "0.1"
lazy_static = "1.4"
nix = "0.19"
rand = "0.7.3"
r2d2 = "0.8.9"
serde = { version = "1.0", features = ["derive"] }
slog = "2.7"
strum_macros = "0.20"
wait-timeout = "0.2"
# local dependencies
ipc = { path = "../../ipc" }
crypto = { path = "../../crypto" }
tezos_api = { path = "../api" }
tezos_context = { path = "../context" }